#! /bin/bash

i0=0
i1=50000
px=physics

args=`getopt 0:1:PMTS $*`

if [ $? != 0 ]
then
    echo 'Usage: daqseq [ -0 <from #> -1 <to #> -PMTS ] <run-number>'
    exit 2
fi
set -- $args

for i
do
    case "$i" in
        -0)
	    i0=$2; shift;
	    shift;;
	-1)
	    i1=$2; shift;
	    shift;;
	-P)
	    px=physics;
	    shift;;
	-M)
	    px=moni;
	    shift;;
	-T)
	    px=tcal;
	    shift;;
	-S)
	    px=sn;
	    shift;;
        --)
            shift; break;;
    esac
done

rn=$1
gap=0

for num in `seq $i0 $i1`; do
    ftst=${px}_${rn}_${num}_*.dat
    if [ -f $ftst ]; then
	gap=0
	echo $ftst
    else
	gap=$[gap+1]
	if [ $gap -gt 1000 ]; then break; fi
    fi;
done
